Repository Game-as-a-Service/IncanGold, pull requests merged in 2023-06, with the labels that each got.

#14 feat: deck style
  frontend/components/decks.vue
  frontend/components/incan-gold-card.vue
  frontend/public/card-back.png
Labels: ✨ feature request

#13 [功能開發] Feature/waiting game avatar
  .gitignore
  frontend/components/game-avatar.vue
  frontend/components/incan-gold-game.vue
  frontend/package.json
  frontend/public/player.png
  frontend/public/player1.png
  frontend/public/player2.png
  frontend/public/player3.png
  frontend/public/player4.png
  frontend/public/player5.png
  package-lock.json
  packages/incan-gold-core/dist/entities/Bag.js
  packages/incan-gold-core/dist/entities/Card/ArtifactCard.js
  packages/incan-gold-core/dist/entities/Card/Card.js
  packages/incan-gold-core/dist/entities/Card/HazardCard.js
  packages/incan-gold-core/dist/entities/Card/TreasureCard.js
  packages/incan-gold-core/dist/entities/Card/index.js
  packages/incan-gold-core/dist/entities/Deck.js
  packages/incan-gold-core/dist/entities/Game.js
  packages/incan-gold-core/dist/entities/Gem.js
  packages/incan-gold-core/dist/entities/Player.js
  packages/incan-gold-core/dist/entities/Temple.js
  packages/incan-gold-core/dist/entities/Tent.js
  packages/incan-gold-core/dist/entities/Tunnel.js
  packages/incan-gold-core/dist/entities/index.js
  packages/incan-gold-core/dist/index.js
  packages/incan-gold-core/dist/useCase/use_case.js
Labels: ✨ feature request

#20 [功能開發] bulletin layout
  frontend/components/game-bulletin.vue
Labels: ✨ feature request

#17 [功能開發] 加入文字設定
  frontend/app.vue
  frontend/components/game-avatar.vue
  frontend/nuxt.config.ts
  frontend/public/Cubic_11_1.013_R.woff2
  frontend/public/Jokerman.ttf
Labels: WIP

#23 [問題修正] 公告卷軸樣式調整
  frontend/components/game-bulletin.vue
Labels: bug
